[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin"
    Permissions-Policy = "geolocation=(self), camera=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' identity.netlify.com; style-src 'self' fonts.googleapis.com; img-src 'self'; font-src 'self'"
    X-Content-Security-Policy = "default-src 'self'; script-src 'self' identity.netlify.com; style-src 'self' fonts.googleapis.com; img-src 'self'; font-src 'self'"
    X-WebKit-CSP = "default-src 'self'; script-src 'self' identity.netlify.com; style-src 'self' fonts.googleapis.com; img-src 'self'; font-src 'self'"
